improve

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -51,8 +51,8 @@ jobs:
           gh pr create --base dummy-main --head release-${date} --title "Release ${date}" --body "Dummy Release PR"
           echo "pr_exit_code=$?" >> "$GITHUB_OUTPUT"
   MetricPublish:
-      needs: [GenerateConfig]
-      if: ${{ always() }}
+      needs: GenerateConfig
+      if: success() || failure()
       runs-on: ubuntu-latest
       permissions:
         id-token: write
@@ -67,13 +67,19 @@ jobs:
           aws-region: us-west-2
       - name: Failure Scenario
         if: ${{ needs.GenerateConfig.result == 'failure' }}
-        run: aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value "-1"
+        run: |
+          echo "ERROR: Encounter error when checking for new release."
+          aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value "-1"
       - name: Release Kickoff Scenario
         if: ${{ needs.GenerateConfig.outputs.stage_exit_code == 1 }}
-        run: aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value 1
+        run: |
+          echo "New updates have been detected. Starting release kickoff"
+          aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value 1
       - name: No Release Scenario
         if: ${{ needs.GenerateConfig.outputs.stage_exit_code == 0 }}
-        run: aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value 0
+        run: |
+          echo "No new release needed at this time."
+          aws cloudwatch put-metric-data --metric-name FluentBitGithubActionTest --namespace FluentBitReleaseTest --value 0
 
     # outputs:
     #   stage_exit_code: ${{ steps.stage.outputs.stage_exit_code }}
